### ISSUE TITLE
"redis-server: not found" when run on Jenkins & RVM Plugin

### ISSUE THREAD

**Issue by thucnh** [phuongnd08/redis_test#8]
Hi Phuong,
I have got the issue when i try to run the redis_test in Jenkins & RVM Plugin
Do you have any idea?
Thanks,
Thuc

sh: 1: redis-server: not found

An error occurred in a `before(:suite)` hook.
Failure/Error: RedisTest.start

RuntimeError:
  Cannot start redis server in 5 seconds. Pinging server yield
  #<Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 9736>

**Comment by phuongnd08** [comment]
You need to have redis-server installed on the machine.
